fix: any-all of fix
bf2fc6cc711aee1a0c2a/kas-fleet-manager pull request #1184
Opened 2022-07-13 15:38 UTC by dimakis

## Description

fixes an issue where openapi generated SDKs can not get list of connectors

fix has already been tested in SDK and works
## Verification Steps

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

2022-07-15 14:51 UTC, VanillaSpoon reviewed
```diff
          {
            "href": "/api/connector_mgmt/v1/kafka_connector_types/OldConnectorTypeStillInUseId",
            "id": "OldConnectorTypeStillInUseId",
            "kind": "ConnectorType",
            "name": "Old Connector Type still in use",
+           "version": ""
          }

```
Add version [Here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/test/integration/features/connector-api.feature#L485) to resolve the CI failing Issues :)

2022-07-15 14:51 UTC, VanillaSpoon commented on openapi/connector_mgmt.yaml
>          Represents a connector type supported by the API
Could remove this split as there's only one line in the description :)
```diff
-      description: >-
-        Represents a connector type supported by the API
+     description: Represents a connector type supported by the API
```

2022-07-18 15:02 UTC, valdar requested changes

2022-07-18 15:11 UTC, dimakis commented on internal/connector/internal/api/admin/private/api/openapi.yaml
> -        - version
that's grand. I've got it updated now. thank you

2022-07-18 15:11 UTC, dimakis commented on internal/connector/internal/api/public/api/openapi.yaml
> -        - version
👍

2022-07-18 15:11 UTC, dimakis commented on openapi/connector_mgmt.yaml
> -            - json_schema
👍

2022-07-18 16:04 UTC, valdar commented on internal/connector/internal/api/admin/private/api/openapi.yaml
> -        - version
@dimakis the name to be kept should be `schema` not `json_schema`. I think you should remove any reference to `json_schema`  in the properties as well: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/f259d085137bb4ff3fe7dfecc4f51320992984df/openapi/connector_mgmt.yaml#L1315

Beside that I think there will be test failures... I think I can take care of those once you finish the changes.

2022-07-19 11:14 UTC, dimakis commented on internal/connector/internal/api/admin/private/api/openapi.yaml
> -        - version
thanks @valdar, I've updated this and removed json_schema

2022-08-01 13:58 UTC, valdar commented
@dimakis if you resolve conflicts I think this is good to be merged

2022-08-01 13:58 UTC, valdar approved these changes

2022-08-01 19:14 UTC, dhirajsb reviewed
@gashcrumb can you check whether the UI has any old references still to `json_schema` anywhere? It probably doesn't, but doesn't hurt to check.

2022-08-02 11:30 UTC, gashcrumb commented
@dhirajsb yep, took a look, besides some test fixtures that need to be updated we don't use that property.

2022-08-02 16:27 UTC, dhirajsb approved these changes
lgtm

2022-08-02 16:27 UTC, merged