Specify the Error schema ref instead of a generic empty object
bf2fc6cc711aee1a0c2a/kas-fleet-manager pull request #1515
Opened 2023-01-25 12:29 UTC by andreaTP

## Description
Generating a client SDK using [Kiota](https://github.com/microsoft/kiota) I found this little inconsistency.
Looking at the rest of the specification seems like `$ref: '#/components/schemas/Error'` is used everywhere but in those two cases left.
I'm not sure if this was done intentionally, but the `example` section is consistent with this proposed change.

## Verification Steps

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

2023-01-25 12:51 UTC, miguelsorianod commented
Adding additional information about the changes in this PR:

The endpoints changed are:
DELETE `/api/kafkas_mgmt/v1/service_accounts/{id}`
POST `/api/kafkas_mgmt/v1/service_accounts/{id}/reset_credentials`

2023-01-25 12:55 UTC, miguelsorianod commented
@akoserwal is there any intentional reason for 5XX responses no error object was returned for the previously mentioned endpoints?

2023-01-26 12:29 UTC, andreaTP commented
Rebased on latest `main` and re-run the generation, but the diff looks huge, am I doing anything wrong?

2023-01-26 12:32 UTC, miguelsorianod commented
> Rebased on latest `main` and re-run the generation, but the diff looks huge, am I doing anything wrong?

I think the reason for that might be that the openapi generator version used to generate the files might be different than the one we use.
The easiest way to ensure the same content is generated is to delete your local `bin` directory in the kfm project and re-run `make generate` again.

2023-01-26 13:25 UTC, machi1990 approved these changes
good catch!

2023-01-26 13:33 UTC, miguelsorianod requested changes
Marking as "request changes" to avoid the merging of the issue until the question about the intentionality of being empty is clarified https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1515#issuecomment-1403563393

2023-02-03 15:20 UTC, andreaTP commented
@miguelsorianod any concern in moving this forward?

2023-02-07 08:37 UTC, akoserwal approved these changes

2023-02-07 08:37 UTC, akoserwal commented
Good catch, lgtm

2023-02-07 09:07 UTC, miguelsorianod approved these changes

2023-02-07 09:07 UTC, merged